name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.0
        with:
          username: "RemcoHalman"
          reponame: "portfolio_website"
          gitemail: "remco.halman@gmail.com"
          gitname: "RemcoHalman"
          gitmsg: "Deploy vue website"
          cname: "remcohalman.nl"
          token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
